### ISSUE TITLE
Batch website is missing overall feature counts

### ISSUE THREAD

**Issue by iandees** [openaddresses/batch#135]
results.openaddresses.io shows the overall row count for the global download as a prominent metric on the top of the page:

![image](https://user-images.githubusercontent.com/261584/111184649-28fde200-857f-11eb-9445-551c84341023.png)

A couple data users have asked me questions about where that count went and if it's gone down with the new download system.

Can we add such a count back to the page? Maybe include counts for parcels and buildings, too?

**Comment by ingalls** [comment]
Already tracking here: https://github.com/openaddresses/batch/issues/34 :)
