### ISSUE TITLE
Cache Map Tiles

### ISSUE THREAD

**Issue by ingalls** [openaddresses/batch#137]
### Context

I get a couple latency alarms a day due to us not caching the map tiles. 

### Actions

- Add a cache for the map tiles

**Comment by iandees** [comment]
The map tiles used in preview image rendering?

**Comment by ingalls** [comment]
@iandees The map tiles on the mainpage that show coverage. Those are regenerated on the fly currently

**Comment by iandees** [comment]
Ah, these: 
![image](https://user-images.githubusercontent.com/261584/111487263-32658680-8706-11eb-9d10-67170612230b.png)
