### ISSUE TITLE
Find another way to build dotmap

### ISSUE THREAD

**Issue by iandees** [openaddresses/batch#155]
The dotmap on openaddresses.io is sourced from [this code](https://github.com/openaddresses/machine/blob/master/openaddr/dotmap.py) that uploads the complete listing of all addresses in OA to Mapbox. This costs a bunch of money, so I disabled the cronjob that runs the dotmap + upload process in AWS.

We need to find another way of generating this layer and keeping it up to date.

**Comment by ingalls** [comment]
We now have a process to fully build a dot map. I'm scaling this out slowly to sources - right now focusing on colorado. As I gain confidence in pricing/scaling I'll continue to roll it out to more area.

To add a source to the Fabric (`/map`) 
1. Be logged in as an admin
2. From the `/data` page find the source and toggle fabric

![Screenshot from 2021-11-01 14-14-58](https://user-images.githubusercontent.com/1297009/139743117-13d293be-5482-40cb-b800-f040c9c24a9d.png)

Once a source is togged on - the fabric must be manually regenerated. 

From the admin page: https://batch.openaddresses.io/profile/admin
A new Fabric batch run can be kicked off
