### ISSUE TITLE
Data Backfill

### ISSUE THREAD

**Issue by ingalls** [openaddresses/batch#24]
### Context

We should backfill the v2 service with all of the last good runs from the results service.

### Actions

-  [x] Write script to get list of s3 locations of latest runs
- [x] Write script to download and convert to GeoJSONLD
- [x] Directly override these files into the database - skipping the runner

cc/ @iandees

**Comment by iandees** [comment]
There's a weekly S3 inventory job that gets run on the data.openaddresses.io bucket. That might be easier to pull down than to list the S3 bucket yourself.

**Comment by ingalls** [comment]
@iandees Oh I'm not familiar with that, is that a native AWS function or something that is integrated into machine? Mind pointing me in the right direction to find this?

**Comment by ingalls** [comment]
This has already happened: https://github.com/openaddresses/batch/issues/38
