### ISSUE TITLE
5XX Investigation

### ISSUE THREAD

**Issue by ingalls** [openaddresses/batch#258]
```
  | 2022-01-26T11:24:06.227-07:00 | ConnectionError: timeout exceeded when trying to connect | batch-prod/api/919a93b15c76439aa5bf8ecbf14288a9
 ```

**Comment by ingalls** [comment]
The root cause determined for the current 5xx errors has been mitigated by entirely removing dynamic tile generation out of the database.

cc/ @iandees - This is the root cause for 3 of the recent support emails related to 5xxs

**Comment by iandees** [comment]
Great work! Glad you found it.
