### ISSUE TITLE
Canada Zip codes, postals and provinces

### ISSUE THREAD

**Issue by smithapuranik** [openaddresses/batch#344]
We need a list of all Canadian postal codes /  use the list of CA zip codes and their provinces. Where can I find this download?
Source of data is ideally a CSV of all Canadian postal codes and their two-character province abbreviations

**Comment by iandees** [comment]
You can find the data we have available at https://batch.openaddresses.io/. I encourage you to download it and see what we have available. Further questions should be directed to https://github.com/openaddresses/openaddresses.
