### ISSUE TITLE
Fabric map is empty

### ISSUE THREAD

**Issue by bertday** [openaddresses/batch#346]
**Describe the bug**
When I go to https://batch.openaddresses.io/map I see an empty map.

**To Reproduce**
1. Go to https://batch.openaddresses.io/map

**Expected behavior**
I expect to see data on the map.

**Screenshots**
![image](https://github.com/openaddresses/batch/assets/1463553/7d58d6ff-bb37-420e-8d4f-da3348ebecb0)

**Desktop (please complete the following information):**
 - OS: macOS 13.3.1
 - Browser: Chrome
 - Version: 114.0.5735.133 (Official Build) (arm64) 

**Additional context**

Happy to help with this if I can!

**Comment by ingalls** [comment]
@rbrtmrtn I'll take a look at migrating. It's currently powered by TileBase, developed at the same time as ProtoMaps. I was doing it on my free time however and with the ProtoMaps integration with Tippecanoe we should make the switch. Right now there is a disparity between versions resulting in the map not populating

**Comment by rbrtmrtn** [comment]
That makes sense @ingalls! I've just started using PMTiles in a project and it's great so far. Much easier to manage than a huge `z/y/x` folder structure 😄

**Comment by bertday** [comment]
It looks like the fabric map has been deprecated (I'm getting a `404` when I visit https://batch.openaddresses.io/map). I'll close this out!

**Comment by iandees** [comment]
I'd like to see us bring it back, also to put on the openaddresses.io homepage. Would you like to file a new issue as a feature request?

**Comment by bertday** [comment]
Just opened #375 for that @iandees!
