### ISSUE TITLE
Job preview/map not showing up

### ISSUE THREAD

**Issue by arch0345** [openaddresses/batch#354]
**Describe the bug**
Preview images from successful jobs are no longer showing up. This affects both the batch website and the [data-please](https://github.com/apps/data-please) bot (ie https://github.com/openaddresses/openaddresses/pull/6673#issuecomment-1658052108)

Additionally, the map showing a bounding box of the job is also not showing up. This seems to also affect the map shown on the [batch homepage](https://batch.openaddresses.io/data)

**To Reproduce**
1. Go to [this page](https://batch.openaddresses.io/job/324990)
2. Under 'Job Preview' the page states that there's 'No Image Preview Found'
3. Click on 'Map' to the right of 'Job Preview'
4. The bounding box shows up for a split second before disappearing. The basemap is also missing.

**Expected behavior**
In the past, successful jobs used to show a preview image of address/parcel/building nodes that were conformed.

**Screenshots**
![image](https://github.com/openaddresses/batch/assets/85302075/a43d73f4-db6b-42d7-8272-b6438cb28134)
![image](https://github.com/openaddresses/batch/assets/85302075/c733cd44-842c-4202-bfdd-627fff7f5249)
![image](https://github.com/openaddresses/batch/assets/85302075/2a726cb7-5355-487e-a33b-6d3d8676cb52)

**Desktop (please complete the following information):**
 - OS: Windows 11 / Android 13
 - Browser: Chrome / Firefox
 - Version: 115 / 115

**Comment by ingalls** [comment]
![image](https://github.com/openaddresses/batch/assets/1297009/10a6ab34-795b-450c-b452-3b9f7702e000)

Fixed.
