### ISSUE TITLE
No indication that download requires login

### ISSUE THREAD

**Issue by davidtorosyan** [openaddresses/batch#357]
**Describe the bug**
Unable to download while logged out. 

Don't know if that's a bug, or the fact that there's no error message.

**To Reproduce**
1. Go to https://batch.openaddresses.io/data while not logged in
2. Click on the download button for `ca`
3. Observe nothing happens

**Expected behavior**
Expected either:
* Download to begin
* Error message asking to login

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Version 116.0.5845.142 (Official Build) (64-bit)

**Comment by ingalls** [comment]
![image](https://github.com/openaddresses/batch/assets/1297009/bf0711d1-5cc9-4230-90ba-413d7f72e65e)

Thanks!
