### ISSUE TITLE
Some sources are missing from /data

### ISSUE THREAD

**Issue by bertday** [openaddresses/batch#370]
**Describe the bug**
Some data sources are missing from https://batch.openaddresses.io/data

**To Reproduce**
1. Go to [https://batch.openaddresses.io/data](https://batch.openaddresses.io/data)
2. Search for `us/ga/washington`

**Expected behavior**
`us/ga/washington` should appear in the list of sources. See screenshot below where it is missing.

**Screenshots**
![image](https://github.com/openaddresses/batch/assets/1463553/1a85d946-1972-480f-9a31-8fa893cfefb5)

**Additional context**
`us/ga/washington` has a source definition here:

https://github.com/openaddresses/openaddresses/blob/master/sources/us/ga/washington.json

added by @arch0345 earlier this year.

**Comment by rbrtmrtn** [comment]
Hi @ingalls, really appreciate you taking a look into this issue of some sources missing from the `/data` page. Just curious if you found any possible culprits, or if there's a way for the OA community to tag in on this one!

**Comment by bertday** [comment]
Hello @ingalls ! I know this was one was a doozy — how did things end up turning out with the re-architecture? Did you have any luck getting the missing sources added back? Are there any opportunities for OA volunteers to tag in?

Thanks again for looking into this one!

**Comment by bertday** [comment]
@ingalls that's great to hear! I just checked `/data` and the things I was expecting are showing up now 🎉  

I'm still seeing some sources missing from the map, but I'll follow up over in #346.

Thanks again!
