### ISSUE TITLE
Running out of storage during Collection creation

### ISSUE THREAD

**Issue by iandees** [openaddresses/batch#385]
Collections haven't updated since mid-March. Looking at [the logs](https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/$252Faws$252Fbatch$252Fjob/log-events/batch-prod-job$252Fdefault$252F33180283e493468bb9ff90fd5669b58d$3Fstart$3D1713101100000$26end$3D1713157199000), it seems that the collection creation job is failing because the instance running this job runs out of disk space:

<img width="946" alt="image" src="https://github.com/openaddresses/batch/assets/261584/fe336377-33ea-4c69-b143-3bec0ea9d81f">

**Comment by iandees** [comment]
I don't see anything in Cloudformation specifying an EBS volume for the batch compute environment, so I think we're using the default root volume in the default AMI. We could create a special-case AMI to use for these Batch jobs that has more storage configured or we could figure out how to attach a second EBS volume just for these jobs? Last I checked, Batch doesn't have great support for this.

**Comment by iandees** [comment]
I made a new Launch Template ([here](https://us-east-1.console.aws.amazon.com/ec2/home?region=us-east-1#LaunchTemplateDetails:launchTemplateId=lt-07a3ddced6598ad6f)) that has default storage of 300GiB instead of 250.

**Comment by iandees** [comment]
I used the Lambda console to manually kick off a `batch-prod-CollectLambdaScheduleFunction` to start the collect process and will see if the extra storage helps.

**Comment by iandees** [comment]
Whatever is starting the EC2 instance used by the `mega` batch compute environment is not using the new launch template, so it's ignoring my storage size change.

**Comment by iandees** [comment]
Nick made a change in 1252532842ae78ddf6a665e00ef5e76a597a71f2 that increased the volume size.

**Comment by ingalls** [comment]
The collection script finished and updated collections are flowing again.
