### ISSUE TITLE
Job previews not loading

### ISSUE THREAD

**Issue by arch0345** [openaddresses/batch#396]
**Describe the bug**
Job previews for successful jobs on the batch site aren't loading. This seems to also affect the preview image for data-please

**To Reproduce**
1. Go to a PR where the data-pls check was successful (ie https://github.com/openaddresses/openaddresses/pull/7364). Notice that there's no preview image.
2. Click on one of the successful jobs (ie https://batch.openaddresses.io/job/436482). Job Sample seems to load indefinitely, Job Statistics and Job Map also aren't showing anything.

**Screenshots**
![image](https://github.com/user-attachments/assets/1b1f3c73-c113-44f1-a706-2c9113926317)
![image](https://github.com/user-attachments/assets/ddcb35c1-438c-4511-ae7c-29486d8c7acd)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome v127/Firefox v129

**Comment by iandees** [comment]
Yea, I'm seeing this too. I'll try to look at the logs later tonight if you don't have a chance to look @ingalls.

**Comment by ingalls** [comment]
![image](https://github.com/user-attachments/assets/99085c86-b556-44f6-b994-ba0366f62c2b)

Fixed, thanks for reporting!
