### ISSUE TITLE
Missing CSV downloads?

### ISSUE THREAD

**Issue by iandees** [openaddresses/batch#79]
In https://github.com/openaddresses/openaddresses/issues/5436, a user points out that they can't find CSV downloads. OpenAddresses data has always distributed CSV data, so switching to line-delimited GeoJSON is a breaking change. Can we add back CSV please?

**Comment by joshbowyer** [comment]
Seconding this, as my own scripts no longer work (merging openaddresses data with OSM data and converting to obf for use with Osmand)

**Comment by iandees** [comment]
In the meantime, you can still download CSVs from results.openaddresses.io.
