### ISSUE TITLE
Reduce costs

### ISSUE THREAD

**Issue by iandees** [openaddresses/batch#87]
After switching to batch, our costs have increased dramatically. At first it was because we were using "optimal" in the AWS Batch configuration, which started rather large instances and kept them running unnecessarily, then after https://github.com/openaddresses/batch/pull/80 we switched to `c5` instances, but AWS Batch is still starting up larger instances and keeping them around for longer than needed. This makes our AWS bill ~twice what it was before we switched to batch.

Can we try to use `c5.large` instances and reduce the maximum number of vCPUs in the batch compute environment? Maybe reduce the requested memory or CPU for each task?

**Comment by ingalls** [comment]
Going to close this. I think we've significantly decreased the costs of the stack to manageable levels for the time being. We can open more strategic tickets as costs warrant
